//	DOOR ON CLOSE
//	WAITS A PERIOD OF TIME BEFORE RELEASING THE PRISONER
//
//	02/06/07	ROBERT HARRIS	ROBERTHARRIS@ROBERTHARRIS.COM
//
//	07/09/07	RFH		ACTIONS NOW ASSIGNED IN JAIL_D_CELL_EN
//
#include "ginc_das_jail"

void main()
{
//	ClearAllActions();
//	ActionLockObject(OBJECT_SELF);
//	ActionWait(JAILTIME);
//	ActionUnlockObject(OBJECT_SELF);
//	ActionOpenDoor(OBJECT_SELF);
//	ActionSpeakString("You are free to go.");
}